Traceback (most recent call last):
  File "C:\Users\seanc\AppData\Roaming\Python\Python38\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\seanc\AppData\Roaming\Python\Python38\site-packages\nbclient\client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\seanc\AppData\Roaming\Python\Python38\site-packages\nbclient\util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\seanc\AppData\Roaming\Python\Python38\site-packages\nbclient\util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "c:\program files\python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\seanc\AppData\Roaming\Python\Python38\site-packages\nbclient\client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "C:\Users\seanc\AppData\Roaming\Python\Python38\site-packages\nbclient\client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\seanc\AppData\Roaming\Python\Python38\site-packages\nbclient\client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
item_neighbors(model,title_substring="Adele", measure='dot', items=artists)
item_neighbors(model, title_substring="Adele", measure='cosine', items=artists)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_13516/1107506850.py[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [0mitem_neighbors[0m[1;33m([0m[0mmodel[0m[1;33m,[0m[0mtitle_substring[0m[1;33m=[0m[1;34m"Adele"[0m[1;33m,[0m [0mmeasure[0m[1;33m=[0m[1;34m'dot'[0m[1;33m,[0m [0mitems[0m[1;33m=[0m[0martists[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      2[0m [0mitem_neighbors[0m[1;33m([0m[0mmodel[0m[1;33m,[0m [0mtitle_substring[0m[1;33m=[0m[1;34m"Adele"[0m[1;33m,[0m [0mmeasure[0m[1;33m=[0m[1;34m'cosine'[0m[1;33m,[0m [0mitems[0m[1;33m=[0m[0martists[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mNameError[0m: name 'model' is not defined
NameError: name 'model' is not defined

